<a href="https://colab.research.google.com/github/aman685892/Data-Analytics-Practice/blob/main/Adding_and_removing_elements_in_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
x=np.array([1,2,3,4,5,6])
print(np.append(x,9))

[1 2 3 4 5 6 9]


In [3]:
y=np.array([[10,20,30],[40,50,60]])
print(np.append(y,[100]))

[ 10  20  30  40  50  60 100]


In [4]:
print(np.insert(x,1,89))

[ 1 89  2  3  4  5  6]


In [5]:
print(np.insert(y,1,[57,37,89]))

[10 57 37 89 20 30 40 50 60]
