<a href="https://colab.research.google.com/github/aman685892/Data-Analytics-Practice/blob/main/Aggregating_Functions_in_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x=np.array([10,20,30,40])
print(x)

[10 20 30 40]


In [9]:
print(np.size(x)) # four elemnts are there in the array
print(np.mean(x))
print(np.sum(x))
print(np.min(x))
print(np.max(x))
print(np.cumsum(x))
print(np.cumprod(x))

4
25.0
100
10
40
[ 10  30  60 100]
[    10    200   6000 240000]


In [15]:
a=[10,20,30,40,50,60]
b=[20,30,40,50,70,90]
price=np.array(a)
quantity=np.array(b)
print(price,quantity)
t=np.cumprod([price,quantity],axis=0)
print(t[1].sum())

[10 20 30 40 50 60] [20 30 40 50 70 90]
12900
