<a href="https://colab.research.google.com/github/aman685892/Data-Analytics-Practice/blob/main/Combining_and_splitting_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
list1=[1,2,3,4]
list2=[2,3,4,5]
print(list1+list2)

[1, 2, 3, 4, 2, 3, 4, 5]


In [4]:
# concatenate
import numpy as np
x=np.array([2,3,4])
y=np.array([5,6,7])
print(np.concatenate([x,y]))

[2 3 4 5 6 7]


In [5]:
import numpy as np
x=np.array([[2,3,4],[4,5,6]])
y=np.array([[5,6,7],[8,4,3]])
print(np.concatenate([x,y],axis=1))

[[2 3 4 5 6 7]
 [4 5 6 8 4 3]]


In [6]:
x=np.array([2,3,4])
y=np.array([5,6,7])
print(np.hstack([x,y])) # hstack is for horizontal concatenation

[2 3 4 5 6 7]


In [7]:
print(np.vstack([x,y]))

[[2 3 4]
 [5 6 7]]


In [8]:
a=np.array([[1,2,3,4,5,6],[2,3,4,5,6,8]])
b=np.array_split(a,3)
print(b)

[array([[1, 2, 3, 4, 5, 6]]), array([[2, 3, 4, 5, 6, 8]]), array([], shape=(0, 6), dtype=int64)]
