<a href="https://colab.research.google.com/github/aman685892/Data-Analytics-Practice/blob/main/Creation%2C_deletion_and_slicing_of_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [14]:
arr=np.array([[1,2,4,5],[4,6,7,8],[7,9,6,5]]) # we will get 3 rows and 4 columns
print(arr)

[[1 2 4 5]
 [4 6 7 8]
 [7 9 6 5]]


In [15]:
y=np.array([56,78,34,89])
print(y[0:])
print(y[1:])
print(y[2:4])
print(y[2:])

[56 78 34 89]
[78 34 89]
[34 89]
[34 89]


In [16]:
z=np.array([[1,3,4,7],[3,5,6,7]])
print(z[0:3,0:2])

[[1 3]
 [3 5]]


In [17]:
print(z[0,1:3]) # 0th index row and columns from 1 to 2

[3 4]


In [20]:
u=np.array([[1,3,4,7],[3,5,6,7],[7,9,3,4]])
print(u[2,2:])  # row number with index 2 and columns from 2-3

[3 4]


In [21]:
print(np.shape(u))

(3, 4)


In [22]:
print(np.size(u))

12


In [23]:
print(np.ndim(u))

2


In [25]:
print(u.dtype)

int64
