<a href="https://colab.research.google.com/github/aman685892/Data-Analytics-Practice/blob/main/Mathematical_operations_on_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
arr1=np.array([13,23,56])
arr2=np.array([23,78,90])
print(arr1+arr2)

[ 36 101 146]


In [15]:
x=np.array([[10,20,30],[40,50,60]])
y=np.array([[30,40,50],[10,30,50]])
print(x+y)
print(np.add(x,y))

[[ 40  60  80]
 [ 50  80 110]]
[[ 40  60  80]
 [ 50  80 110]]


In [16]:
import numpy as np
arr1=np.array([13,23,56])
arr2=np.array([23,78,90])
print(arr1-arr2)

[-10 -55 -34]


In [17]:
import numpy as np
arr1=np.array([13,23,56])
arr2=np.array([23,78,90])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[ 299 1794 5040]
[ 299 1794 5040]


In [18]:
import numpy as np
arr1=np.array([13,23,56])
arr2=np.array([23,78,90])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[0.56521739 0.29487179 0.62222222]
[0.56521739 0.29487179 0.62222222]


In [19]:
arr1=np.array([13,23,56])
arr2=np.array([2])
print(np.power(arr1,arr2))

[ 169  529 3136]


In [21]:
u=np.array([16,81,9,100])
print(np.sqrt(u))
print(np.sqrt(u).astype(int))

[ 4.  9.  3. 10.]
[ 4  9  3 10]
