<a href="https://colab.research.google.com/github/aman685892/Data-Analytics-Practice/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
l1=[20,30,40]
l2=[4,5,6]
print(l1+l2)

[20, 30, 40, 4, 5, 6]


In [7]:
a=np.array([1,2,3,4])
b=np.array([4,6,9,7])
print(a)
print(b)

print(a+b)

[1 2 3 4]
[4 6 9 7]
[ 5  8 12 11]


In [8]:
a=np.array([1,2,3,"aman"]) ## if one string is passed all elemnets will be string
print(a)

['1' '2' '3' 'aman']


In [9]:
l3=[[1,2,3],[5,6,7]]
print(l3)

[[1, 2, 3], [5, 6, 7]]


In [11]:
x=np.array([[1,2,3],[3,4,5]])
print(x)

[[1 2 3]
 [3 4 5]]
