<a href="https://colab.research.google.com/github/aman685892/Data-Analytics-Practice/blob/main/Search%2C_filter_and_sort_in_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
x=np.array([100,70,80,40])
print(np.sort(x))

[ 40  70  80 100]


In [3]:
y=np.array([[100,20,80],[50,10,40]])
print(np.sort(y))

[[ 20  80 100]
 [ 10  40  50]]


In [5]:
## searching in array
z=np.array([10,20,30,40])
print(np.where(z==30))
print(np.where(z%2==0))

(array([2]),)
(array([0, 1, 2, 3]),)


In [6]:
## searching if the elements are sorted
u=np.array([10,20,30,40])
print(np.searchsorted(u,30))

2


In [8]:
import numpy as np
w=np.array([10,20,30,40])
fa=[True,False,True,False]
k=w[fa]
print(k)

[10 30]


In [9]:
L=np.array([12,24,36,48])
fa=L%2==0
b=L[fa]
print(b)

[12 24 36 48]
